### PR TITLE
Money out of thin air and no money from critters

### PR DESCRIPTION
**Pull request by Kunepro**
Hi,

I made some changes to add two options.

The first one is to not give players any reward for passive or faction creatures, the other one generates the money out of nothing instead of taking them from the kingdom coffers.

I was unable to test the mod because I receive this error and I don't know how to handle it:

```
        catch (NotFoundException | CannotCompileException e) {
            logger.log(Level.SEVERE, "Error editing functions:", e);
            e.printStackTrace();
        }
```

Error:(250, 38) java: multi-catch statement is not supported in -source 1.6
  (use -source 7 or higher to enable multi-catch statement)

Can you either teach me how to solve that error or just test the mod?
I also didn't knew how to compile the mod into a jar later anyways...

### CODE REVIEW

**Comment by WalkerInTheVoid** [comment]
First off, apologies, did the latest release and only then noticed the pull request >_<  Still learning about GitHub, what can I say.

Anyway, second, these are pretty good ideas, and nice work too.
Third, the error seems to be that you're using an older version of Java.  I'm compiling against jre 1.8.0_65, for reference.

**Comment by WalkerInTheVoid** [comment]
One quibble: I'm seeing where outOfThinAir and CritterNoBounties are called, but not where they're declared (private boolean yaddayadda)

**Comment by Kunepro** [comment]
My jdk is :"jdk1.8.0_65", so it's the same, but I'm not a Java programmer, and I actually don't know how to create and artefact and stuff like that to then compile and test the mod.

I added the variable's declarations, then delete them to change something, and then it looks like I just forgot to re-add them.

I can't work on this until the weekend, if you like you can merge the changes manually and I will delete the pull request, or merge normally and fix the remaining problems yourself (not to be rude, it's just that I'm back at work and the free time is pretty much nil).

Let me know what you choose.

Thanks,
Nik

**Comment by WalkerInTheVoid** [comment]
Nothing rude, was actually already doing the manual merge.  Only errors are the declarations and a capitalization typo (getKingdomID vs getKingdomId) that it took me a bit to realize WAS a typo, so...really the delay is that I use Eclipse and Egit, and Egit's design clearly did not include pull requests >_<

**Comment by WalkerInTheVoid** [comment]
Well, I'm not yet sure how I should have merged that, but pretty sure the way I did it isn't the ideal.  Still, it's merged, about to do some testing on it before a quick release, and also thanks to you I spotted a bug in that the pay-to-bank option meant the money was in fact coming out of thin air and not the kingdom coffers!  Whooops.

So yeah, thanks again :)

**Pull request merged**
